### ISSUE TITLE
Can't Install Any Plugins Without Entering FTP Connection Info

### ISSUE THREAD

**Issue by fatihturan** [jaredpalmer/presspack#42]
Hi,

I really like the Presspack and installed it successfully. But when I want to install the plugin from the admin panel, Wordpress asking me connection information for FTP.

![image](https://user-images.githubusercontent.com/26871/81498982-b114ba80-92d0-11ea-8902-7fcc20f34f27.png)

Also, I've modified the docker-compose.yml file like below:

```
version: '3.3'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress
    volumes:
      - "./template:/var/www/html/wp-content/themes/presspack"
      - "./build:/var/www/html/wp-content/themes/presspack/build"
      - "./wp-content/:/var/www/html/wp-content/"
      - "./wp-content/plugins:/var/www/html/wp-content/plugins"
      - "./wp-content/uploads:/var/www/html/wp-content/uploads"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    links:
      - db
    ports:
      - "9009:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      user: root
```

So what's wrong with it?

**Comment by fatihturan** [comment]
Oh, I found a quick solution to this problem by changing volume lines:

```
version: '3.3'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress
    volumes:
      - "./template:/var/www/html/wp-content/themes/presspack"
      - "./build:/var/www/html/wp-content/themes/presspack/build"
      - "./wp-content/:/var/www/html/wp-content/"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    links:
      - db
    ports:
      - "9009:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
```
